#!/bin/bash
# ===============================================================
# date       : 21 maio 2013 15h53
# author     : fmv
# decription : convert POSCAR (vasp) to POSFF (mdff)
# ===============================================================
separetor="=========================================================="
USAGE="Usage: -i [inputfile] -l [n_last_steps] -n <0 or 1>"

no=0
if [ $# -eq 0 ]
then
    echo "$USAGE"
    exit 1
fi
while getopts ":i:l:n:" opt
do
    case $opt in
        i)
            osziff="$OPTARG"
            ;;
        l)
            last="$OPTARG"
            ;;
        n)
            no="$OPTARG"
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done
if [ $no -eq 0 ];
then
	echo $separetor
	date
	echo "author : filipe.manuel.vasconcelos@gmail.com"
	echo $separetor
	echo "Running averoszi ..."
	echo "This script calculate simple average value along OSZIFF file"
fi

echo "generate etot and temp files"
echo ""
grep Etot $osziff > etot
grep Temp $osziff > temp
npoints=`wc etot | awk '{print $1}'`
echo "$npoints points in input file $osziff"
if [ -z "$last" ];
then
	last=$npoints
fi 
tail -n $last etot > etot_l
tail -n $last temp > temp_l

echo ""
echo "averaging on $last last points:"
echo ""
awk -v np=$last     'BEGIN  { sum_etot=0       ; sum_ekin=0    ; sum_utot=0    ; sum_ulj=0    ; sum_ucoul=0    ; sum_umorse=0 } 
                            { sum_etot+=$9     ; sum_ekin+=$12 ; sum_utot+=$15 ; sum_ulj+=$18 ; sum_ucoul+=$21 ; sum_umorse+=$24 } 
                      END   { printf("%10s %12.5f\n%10s %12.5f\n%10s %12.5f\n%10s %12.5f\n%10s %12.5f\n%10s %12.5f\n",     "<Etot>=",sum_etot/np,
                                                                                                                           "<Ekin>=",sum_ekin/np,
                                                                                                                           "<Upot>=",sum_utot/np,
                                                                                                                           "<Ulj>=",sum_ulj/np,
                                                                                                                           "<Ucoul>=",sum_ucoul/np,
                                                                                                                           "<Umorse>=",sum_umorse/np ) }' etot_l

awk -v np=$last     'BEGIN  { sum_temp=0       ; sum_press=0    ; sum_Plj=0    ; sum_Pcoul=0    ; sum_volume=0 } 
                            { sum_temp+=$9     ; sum_press+=$12 ; sum_Plj+=$15 ; sum_Pcoul+=$18 ; sum_volume+=$21 } 
                      END   { printf("%10s %12.5f\n%10s %12.5f\n%10s %12.5f\n%10s %12.5f\n%10s %12.5f\n",                  "<Temp>=",sum_temp/np,
                                                                                                                           "<Press>=",sum_press/np,
                                                                                                                           "<Plj>=",sum_Plj/np, 
                                                                                                                           "<Pcoul>=",sum_Pcoul/np,
                                                                                                                           "<vol>=", sum_volume/np ) }' temp_l

if [ $no -eq 0 ];
then
	echo $separetor
fi
exit 0;

