#!/bin/bash
# ===============================================================
# date       : 21 maio 2013 15h53
# author     : fmv
# decription : convert POSCAR (vasp) to POSFF (mdff)
# ===============================================================
separetor="=========================================================="
echo $separetor
date
echo "author : filipe.manuel.vasconcelos@gmail.com"
echo $separetor
echo "Running poszi ..."
echo "This script generate gnuplot plots from input OSZIFF file"
USAGE="Usage: -i [inputfile] -l [n_last_steps] "

if [ $# -eq 0 ]
then
    echo "$USAGE"
    exit 1
fi
while getopts ":i:l:" opt
do
    case $opt in
        i)
            osziff="$OPTARG"
            ;;
        l)
            last="$OPTARG"
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

echo ""
echo "running averoszi script : simple averaging"
if [ -z "$last" ];
then
	averoszi -n 1 -i $osziff | tee out_aver
else
	averoszi -n 1 -i $osziff -l $last | tee out_aver
fi
echo ""
etot_aver=`tail -n 11 out_aver | head -n 1 | awk '{print $NF}'`
epot_aver=`tail -n  9 out_aver | head -n 1 | awk '{print $NF}'`
temp_aver=`tail -n  5 out_aver | head -n 1 | awk '{print $NF}'`

echo "plot total energy evolution"
cat > plot.etot << eof
#!/usr/bin/gnuplot 
reset
set term x11
set title "Total energy MD"
set xlabel "#n step"
set ylabel "E_{tot}"
p 'etot_l' u 3:9 w lp title '',\
  $etot_aver title ""
pause -1
eof
chmod u+x plot.etot
./plot.etot

echo "plot potential energy evolution"
cat > plot.econf << eof
#!/usr/bin/gnuplot 
reset
set term x11
set title "Potential energy MD"
set xlabel "#n step"
set ylabel "E_{pot}"
p 'etot_l' u 3:15 w lp title '',\
  $epot_aver title ""
pause -1
eof
chmod u+x plot.econf
./plot.econf

echo "plot temperature evolution"
cat > plot.temp << eof
#!/usr/bin/gnuplot 
reset
set term x11
set title "Temperature MD"
set xlabel "#n step"
set ylabel "T"
p 'temp_l' u 3:9 w lp title '',\
  $temp_aver title ""
pause -1
eof
chmod u+x plot.temp
./plot.temp

rm plot.temp plot.etot plot.econf
echo $separetor
exit 0;

